### ISSUE TITLE
cant open existing boards

### ISSUE THREAD

**Issue by Istvan101** [Holo-Host/talking-stickies#8]
as per the title says, the boards are there but after selecting one and opening it, out of 3 boards, only 1 opens. I am an end user, no expert. Update. And now it suddenly opens again. all of them.

**Comment by MatthewNichols** [comment]
I ran into this too, I think it because data is still syncing. But a UI indication would be nice.

**Comment by thedavidmeister** [comment]
couldn't open a board at all, clicked it from the dropdown but GUI did not update
